[package]
name = "substrate-subxt-proc-macro"
version = "0.7.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
autotests = false

[lib]
proc-macro = true

[dependencies]
heck = "0.3.1"
proc-macro2 = "1.0.10"
proc-macro-crate = "0.1.4"
quote = "1.0.3"
syn = "1.0.17"
synstructure = "0.12.3"

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
codec = { package = "parity-scale-codec", version = "1.2.0", features = ["derive"] }
env_logger = "0.7.1"
pretty_assertions = "0.6.1"
sp-keyring = "2.0.0-alpha.7"
substrate-subxt = { path = ".." }
trybuild = "1.0.25"

[[test]]
name = "balances"
path = "tests/balances.rs"
