[package]
name = "parachain-example"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
subxt = { path = "../../subxt" }
subxt-signer = { path = "../../signer" }
tokio = { version = "1.28", features = ["macros", "time", "rt-multi-thread"] }
